Inafocam.Web/Areas/Profesores/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Andamios.Web.Helpers;
using Inafocam.core.Interfaces;
using Inafocam.core.Modelos;
using Inafocam.core.Utilidades;
using Inafocam.Web.Areas.Profesores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Inafocam.Web.Areas.Profesores.Controllers
{
    [Area("Profesores"), ReturnArea("Profesores")]
    [ReturnControllador("Profesores"), ReturnController("Profesores")]
    public class ProfesorController : Controller
    {
        private readonly ITeacher _teacher;
        private readonly IContactType _contactType;
        private readonly IDocumentType _documentType;
        private readonly ICountry _country;
        private readonly ICity _city;
        private readonly IAddressType _addressType;
        private readonly IStatus _status;
        private readonly IEducationType _educationType;
        private readonly ITeacherEducation _teacherEducation;
        private readonly ITeacherFileType _teacherFileType;
        private readonly INationality _nationality;
        private readonly IMatirialStatus _matirialStatus;
        private readonly IProvince _province;
     

        public ProfesorController(ITeacher teacher, IContactType contactType, 
            IDocumentType documentType, ICountry country ,ICity city,
            IAddressType addressType, IStatus status, IEducationType educationType,
            ITeacherEducation teacherEducation, INationality nationality, IMatirialStatus matirialStatus, IProvince province
            )
        {
            _teacher = teacher;
            _contactType = contactType;
            _documentType = documentType;
            _country= country;
            _city= city;
            _addressType= addressType;
            _status = status;
            _educationType = educationType;
            _teacherEducation = teacherEducation;
            _nationality = nationality;
            _matirialStatus = matirialStatus;
            _province = province;
        }

        public IActionResult Index()
        {
            var teachers = _teacher.GetAll;

            return View(teachers);
        }  
        
        public IActionResult Crear(TeacherModel model)
        {


            //var model = CopyPropierties.Convert<Teacher, TeacherModel>(data);
            ViewBag.ContactTypes = new SelectList(_contactType.GetAll, "ContactTypeId", "ContactTypeName");
            ViewBag.DocumentType = new SelectList(_documentType.GetAll, "DocumentTypeId", "DocumentTypeName");
            ViewBag.Countries = new SelectList(_country.GetAll, "CountryId", "CountryName");
            ViewBag.Cities = new SelectList(_city.Cities, "CityId", "CityName");
            ViewBag.AddressTypes = new SelectList(_addressType.addressTypes, "AddressTypeId", "AddressTypeName");
            //ViewBag.Status = new SelectList(_status);
            ViewBag.EducationType = new SelectList(_educationType.GetAll, "EducationTypeId", "EducationTypeName");
            ViewBag.TeacherEducation = new SelectList(_teacherEducation.GetAll, "TeacherEducationId", "TeacherEducationTitle");
            ViewBag.Nationality = new SelectList(_nationality.GetAll, "NationalityId", "NationalityName");
            ViewBag.MatirialStatus = new SelectList(_matirialStatus.GetAll, "MaritalStatusId", "MaritalStatusName");
            //genre

            return View(model);
        }

        public IActionResult Editar(int id)
        {
            var data = _teacher.GetById(id);

          var model =   CopyPropierties.Convert<Teacher, TeacherModel>(data);
            ViewBag.ContactTypes = new SelectList(_contactType.GetAll, "ContactTypeId", "ContactTypeName");
            ViewBag.DocumentType = new SelectList(_documentType.GetAll, "DocumentTypeId", "DocumentTypeName");
            ViewBag.Countries = new SelectList(_country.GetAll, "CountryId", "CountryName");
            ViewBag.Cities = new SelectList(_city.Cities, "CityId", "CityName");
            ViewBag.AddressTypes = new SelectList(_addressType.addressTypes, "AddressTypeId", "AddressTypeName");
            //ViewBag.Status = new SelectList(_status);
            ViewBag.EducationType = new SelectList(_educationType.GetAll, "EducationTypeId", "EducationTypeName");
            ViewBag.TeacherEducation = new SelectList(_teacherEducation.GetAll, "TeacherEducationId", "TeacherEducationTitle");
            ViewBag.Nationality = new SelectList(_nationality.GetAll, "NationalityId", "NationalityName");
            ViewBag.MatirialStatus = new SelectList(_matirialStatus.GetAll, "MaritalStatusId", "MaritalStatusName");

            return View("Crear",model);
        }

        public IActionResult Guardar(TeacherModel model)
        {

            try
            {
                var data = CopyPropierties.Convert<TeacherModel, Teacher>(model);
                _teacher.Save(data);
            }
            catch (Exception e)
            {
                //var model = CopyPropierties.Convert<Teacher, TeacherModel>(data);
                //ViewBag.ContactTypes = new SelectList(_contactType.GetAll, "ContactTypeId", "ContactTypeName");
                //ViewBag.DocumentType = new SelectList(_documentType.GetAll, "DocumentTypeId", "DocumentTypeName");
                //ViewBag.Countries = new SelectList(_country.Country, "CountryId", "CountryName");
                //ViewBag.Cities = new SelectList(_country.Country, "CityId", "CityName");
                //ViewBag.AddressTypes = new SelectList(_addressType.addressTypes, "AddressTypeId", "AddressTypeName");
                ////ViewBag.Status = new SelectList(_status);
                //ViewBag.EducationType = new SelectList(_educationType.GetAll, "EducationTypeId", "EducationTypeName");
                //ViewBag.TeacherEducation = new SelectList(_teacherEducation.GetAll, "TeacherEducationId", "TeacherEducationTitle");
                //ViewBag.Nationality = new SelectList(_nationality.GetAll, "NationalityId", "NationalityName");
                //ViewBag.MatirialStatus = new SelectList(_matirialStatus.GetAll, "MaritalStatusId", "MaritalStatusName");

                //return View("Crear", model);
            }


            return View("Index", _teacher.GetAll);
        }

    }
}

Inafocam.Web/Areas/Profesores/Views/Profesor/Crear.cshtml
@using Andamios.Web.Helpers
@using Microsoft.AspNetCore.Razor.Language.CodeGeneration
@model Inafocam.Web.Areas.Profesores.Models.TeacherModel

@{ ViewData["Title"] = "Create";

    MensajesViewModel mensaje = new MensajesViewModel();

    if (TempData["mensaje"] != null)
    {

        mensaje = TempData.Get<MensajesViewModel>("mensaje");

    } }

@section Style
{
    <link href="~/app-assets/vendors/noUiSlider/nouislider.css" rel="stylesheet" />
    <link href="~/app-assets/css/custom/custom.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
}


@* BREADCRUMB *@
@await Component.InvokeAsync("BreadcrumbComponent", new
{
    area = (string)ViewData["area"],
    controlador = (string)ViewData["controlador"],
    controller = (string)ViewData["controller"],
    vista = (string)ViewData["vista"]
})
@* END BREADCRUMB *@



<div class="row">
    <form class="col s12 formValidate" method="post" asp-area="Profesores" asp-controller="Profesor" asp-action="Guardar">

        <input type="hidden" asp-for="TeacherId" />
        <input type="hidden" asp-for="ContactId" />
        <input type="hidden" asp-for="StatusId" />
        <input type="hidden" asp-for="HigherTeacherEducation.StatusId" />
        <input type="hidden" asp-for="HigherTeacherEducation.TeacherId" />
        <input type="hidden" asp-for="HigherTeacherEducation.TeacherEducationId" />
        <input type="hidden" asp-for="HigherTeacherEducationId" />
        <input type="hidden" asp-for="TeacherHiringTypeId" />
  


        <div>
            <span asp-validation-sumary=""></span>
        </div>


        @{ var prueba = Model.Contact?.ContactName; }



        <div class="card">
            <div class="card-content">

                <h4 class="card-title">Información Personal</h4>

                <div class="row ">


                    <div class="input-field col s12 m6 l3">

                        @*<i class="material-icons prefix">contacts</i>*@

                        <input value="lll" id="id" type="text" class="validat" disabled style="font-weight: bold;">

                        <label for="id">Teacher ID</label>


                    </div>


                    <div class="input-field col s12 m6 l3">
                        <input asp-for="Contact.ContactName" id="nombre" type="text" class="validate">
                        <label for="nombre">Nombre</label>
                        <span class="red-text validationDisplay"></span>
                    </div>

                    <div class="input-field col s12 m6 l3">
                        <input asp-for="Contact.ContactLastname" id="apellido" type="text" class="validate">
                        <label for="apellido">Apellido</label>
                        <span class="red-text validationDisplay"></span>
                    </div>

                    <div class="input-field col s12 m6 l3">
                        <div class="row">
                            <label for="select2User" class="col s12">Genero</label>
                        </div>
                        <select class="form-control js-example-basic-single" style="width: 100%">
                        </select>


                    </div>

                </div>

                <div class="row">

                    <div class="input-field col s12 m6 l3">
                        <div class="row">
                            <label for="select2User" class="col s12">Tipo de Documento</label>
                        </div>
                        <select asp-for="Contact.ContactTypeId" class="form-control js-example-basic-single" style="width: 100%" asp-items="ViewBag.ContactTypes">
                        </select>


                    </div>

                    <div class="input-field col s12 m6 l3">
                        <div class="row">
                            <label for="select2User" class="col s12">Tipo de Contacto</label>
                        </div>
                        <select asp-for="Contact.DocumentType" class="form-control js-example-basic-single" style="width: 100%" asp-items="ViewBag.DocumentType">
                        </select>


                    </div>


                    <div class="input-field col s12 m6 l3">
                        <input asp-for="Contact.ContactDocumentNumber" id="numerodocumento" type="text" class="validate">
                        <label for="numerodocumento">Numero del Documento</label>
                        <span class="red-text validationDisplay"></span>
                    </div>

                    <div class="input-field col s12 m6 l3">
                        <div class="row">
                            <label for="select2User" class="col s12">Nacionalidad</label>
                        </div>
                        <select asp-for="Contact.ContactNationalityId" class="form-control js-example-basic-single" style="width: 100%" asp-items=" ViewBag.Nationality">
                        </select>


                    </div>

                </div>



                <div class="row">








                    <div class="input-field col s12 m6 l4">
                        <input asp-for="Contact.ContactBornPlace" id="lugarnacimiento" type="text" class="validate">
                        <label for="lugarnacimiento">Lugar de Nacimiento</label>
                        <span class="red-text validationDisplay"></span>
                    </div>

                    <div class="input-field col s12 m6 l4">
                        <input asp-for="Contact.ContactBornDate" id="fechanacimiento" type="text" class="datepicker">
                        <label for="fechanacimiento">Fecha de Nacimiento</label>
                        <span class="red-text validationDisplay"></span>
                    </div>






                    <div class="input-field col s12 m6 l4">
                        <div class="row">
                            <label for="select2User" class="col s12">Estado de Material</label>
                        </div>
                        <select asp-for="Contact.ContactMaritalStatusId" class="form-control js-example-basic-single" style="width: 100%" asp-items="ViewBag.MatirialStatus">
                        </select>


                    </div>



                </div>

            </div>



        </div>

        <div class="card">
            <div class="card-content">

                <h4 class="card-title">Información Academica</h4>

                <div class="input-field col s12 m6 l6">
                    <input asp-for="TeacherResearchProcess" id="enproceso" type="number" class="validate">
                    <label for="enproceso">En Proceso</label>
                    <span class="red-text validationDisplay"></span>
                </div>

                <div class="input-field col s12 m6 l6">
                    <input asp-for="TeacherResearchPublished" id="publicado" type="number" class="validate">
                    <label for="publicado">Publicado</label>
                    <span class="red-text validationDisplay"></span>
                </div>
            </div>
        </div>


        <div class="card">
            <div class="card-content">

                <h4 class="card-title">Agregar Preparación Académica</h4>




                <div class="input-field col s12 m6 l3">
                    <input asp-for="HigherTeacherEducation.TeacherEducationTitle" id="tituloeducacion" type="text" class="validate">
                    <label for="tituloeducacion">Titulo de la Educacion</label>
                    <span class="red-text validationDisplay"></span>
                </div>

                <div class="input-field col s12 m6 l3">
                    <input asp-for="HigherTeacherEducation.TeacherEducationInstitution" id="institucionformadora" type="text" class="validate">
                    <label for="institucionformadora">Institucion Formadora</label>
                    <span class="red-text validationDisplay"></span>
                </div>

                <div class="input-field col s12 m6 l3">
                    <input asp-for="HigherTeacherEducation.TeacherEducationFinishDate" id="fechatermino" type="text" class="datepicker">
                    <label for="institucionformadora">Fecha de Término</label>
                    <span class="red-text validationDisplay"></span>
                </div>

                <div class="input-field col s12 m6 l3">
                    <div class="row">
                        <label for="select2User" class="col s12">Tipo de Educacion</label>
                    </div>
                    <select asp-for="HigherTeacherEducation.EducationTypeId" class="form-control js-example-basic-single" style="width: 100%" asp-items="ViewBag.EducationType">
                    </select>


                </div>

            </div>
        </div>

        <div class="input-field col s12">

            <button class="teal btn waves-effect waves-light" type="submit">
                <i class="material-icons left">save</i>
                Guardar
            </button>



            <a class="red btn waves-effect waves-light">
                <i class="material-icons left">cancel</i>
                Anular
            </a>

            <a class="white btn waves-effect waves-light black-text">
                <i class="material-icons left">cleaning_services</i>
                Limpiar
            </a>

        </div>

    </form>


</div>

@section Scripts
{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/app-assets/vendors/jquery-validation/jquery.validate.js"></script>
    <script src="~/app-assets/vendors/jquery-validation/additional-methods.js"></script>
    <script src="~/app-assets/vendors/jquery-cookies/jquery.cookies.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <!-- BEGIN VENDOR JS-->
    <script src="~/app-assets/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN THEME JS-->
    <script src="~/app-assets/js/plugins.js" type="text/javascript"></script>
    <script src="~/app-assets/js/custom/custom-script.js" type="text/javascript"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/app-assets/js/toastr.init.js" type="text/javascript"></script>
    <script src="~/app-assets/vendors/formatter/jquery.formatter.min.js" type="text/javascript"></script>
    @*<script src="~/app-assets/js/scripts/form-elements.js"></script>
        <script src="~/app-assets/js/scripts/form-masks.js"></script>
        @*<script src="~/app-assets/js/scripts/form-layouts.js" type="text/javascript"></script>*@
    @*<script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <!-- END PAGE LEVEL JS-->
    <script>
        @*$('#descripcionTxtArea').val('@Model.Descripcion');
        M.textareaAutoResize($('#textarea2'));*@


        $(document).ready(function () {
            $('.js-example-basic-single').select2({
                placeholder: "Select a state",
            });
        });

        //document.addEventListener('DOMContentLoaded', function () {
        //    var elems = document.querySelectorAll('.datepicker');
        //    var instances = M.Datepicker.init(elems, options);
        //});

        // Or with jQuery

        $(document).ready(function () {
            $('.datepicker').datepicker();
        });

    </script>
}

Inafocam.Web/Areas/Profesores/Views/Profesor/Index.cshtml
@model IEnumerable<Inafocam.core.Modelos.Teacher>

@section Style
{
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/flag-icon/css/flag-icon.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/data-tables.css">

    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/css/select.dataTables.min.css">
    <!-- END: VENDOR CSS-->
    <!-- BEGIN: Page Level CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/custom/custom.css">
    <!-- END: Custom CSS-->
    @*<link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />*@
    @*<link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />*@
    <link href="~/lib/jquery-confirm/dist/jquery-confirm.min.css" rel="stylesheet" />

}

@* BREADCRUMB *@
@await Component.InvokeAsync("BreadcrumbComponent", new
{
    area = (string)ViewData["area"],
    controlador = (string)ViewData["controlador"],
    controller = (string)ViewData["controller"],
    vista = (string)ViewData["vista"]
})
@* END BREADCRUMB *@



@* RAZOR *@
<!-- Page Length Options -->
<div class="section section-data-tables">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <div class="row">

                        <div class="col s6 ">


                            <a class="teal mb-1 btn-small waves-effect waves-light " data-position="top" asp-area="Profesores" asp-controller="Profesor" asp-action="Crear">
                                <i class="material-icons">add</i>
                                Nuevo
                            </a>

                            <a class=" red mb-1 btn-small waves-effect waves-light" data-position="top" href="#">
                                <i class="material-icons">cancel</i>
                                Anular
                            </a>

                            <a class=" mb-1 btn-small white black-text waves-effect waves-light" data-position="top" data-tooltip="Cambiar estado" href="#">
                                <i class="material-icons">print</i>
                                Imrimir
                            </a>

                        </div>
                        @*<div class="offset-6 right ">

                                <a class="grey mb-1 btn-small waves-effect waves-light tooltipped" data-position="left" data-tooltip="Lista de roles" >
                                    <i class="material-icons">verified_user</i>
                                   Roles
                                </a>

                            </div>*@

                    </div>
                    <div class="col s12">

                        <div class="row">
                            <div class="grid-example col s12" style="margin:0px;"><span class="flow-text"></span></div>
                        </div>
                        <br />
                        @*<a class="mb-1 btn waves-effect waves-light teal darken-1" asp-area="Clientes" asp-controller="Cliente" asp-action="Create"><i class="material-icons">add</i> Agregar</a>*@

                        <div class="row">
                            <div class="col s12">
                                @await Component.InvokeAsync("TeacherDataTableComponent")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
@* END MODAL *@

@* END RAZOR *@

@section Scripts
{
    <!-- BEGIN VENDOR JS-->
    <script src="~/app-assets/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/app-assets/vendors/data-tables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="~/app-assets/vendors/data-tables/js/dataTables.select.min.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN THEME  JS-->
    <script src="~/app-assets/js/plugins.js" type="text/javascript"></script>
    <script src="~/app-assets/js/custom/custom-script.js" type="text/javascript"></script>
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/app-assets/js/scripts/data-tables.js" type="text/javascript"></script>
    <script src="~/app-assets/js/scripts/extra-components-sweetalert.js" type="text/javascript"></script>
    <script src="~/lib/jquery-confirm/dist/jquery-confirm.min.js"></script>
    @*<script src="~/lib/toastr.js/toastr.min.js"></script>
        <script src="~/app-assets/js/toastr.init.js" type="text/javascript"></script>*@

    <script src="/app-assets/js/scripts/advance-ui-modals.js"></script>
}